### ISSUE TITLE
Changing $brand-primary do not affect cards header

### ISSUE THREAD

**Issue by speller** [creativetimofficial/material-kit#105]
Card header color definitions are hardcoded to color names in the `_cards.scss` and do not depend on $brand-primary variable value. You have to edit css class and its gradient definition instead of changing theme color variables.

**Comment by dragosct10** [comment]
Hi, @speller! Yes, do you have right about it. If you want to change the colors from the gradient of the card-header you can change from the partial `_cards.scss`. 

Regards,
Dragos

**Comment by speller** [comment]
@dragosct10 I don't agree with you. If a card has the `card-header-primary` class it should have color of the primary theme color. Like btn-primary, according to the Bootstrap class names scheme.

**Comment by dragosct10** [comment]
Hi, @speller! Yes, this makes sense, but we made more tests of styling and we agree that a gradient-color applied on the card-header would be more special and attractive because just to put a simple purple color will not be such special and for us, the details are the most important. The gradient color from card-header is present also in the BS3 Version. 

Regards,
Dragos

**Comment by speller** [comment]
@dragosct10 I see. But why not to use scss color modification functions when creating beginning and ending colors to create variations of the arbitrary main color?

**Comment by dragosct10** [comment]
Hi, @speller! Your idea 's not bad. We will take into consideration this and in the next update, we will integrate. Thank you. 

Regards, Dragos
