### ISSUE TITLE
scss not working on rails (5)

### ISSUE THREAD

**Issue by michelson** [creativetimofficial/material-kit#106]
just copied the files and add it to application.scss

`@import "scss/material-kit-pro.scss";`

lot sass of errors!! im using pro kit

**Comment by dragosct10** [comment]
Hi, @michelson! Thank you for using our product. What errors did you have? Regards, Dragos.

**Comment by feliksby** [comment]
same here! A lot of errors!!

**Comment by krabique** [comment]
There seem to be a problem with missing `/material-kit/assets/img/arrow-left.cur` and `/material-kit/assets/img/arrow-left.png`. Both `.css` and `.scss` won't resolve those arrow assets (they are simply not there). Same for `arrow-right`. I'm using the free npm package and loading it through `webpacker` gem.

**Comment by michelson** [comment]
well, it should be easy for you guys to put the scss files info the rails asset pipeline and execute rails s, don't expect that people who bought your product reproduce the bug for you. It a shame that this has been reported 20 days ago and we have no responses yet ??.

I've been able to fix this by commenting & rewriting some of the sass code , it has to be with the compiler complaining with nested & , and other stuff, but just  `@import "scss/material-kit-pro.scss"` into a blank rails project and try it out!

**Comment by alexandru-paduraru** [comment]
@michelson please open the issue on the PRO repo (https://github.com/creativetimofficial/material-kit-pro/issues/new), in this way you will get a better priority for our support. At this moment our Free products are used by hundreds of thousands of people and we have a lot of developers requesting/reporting a lot of things. This is the reason we split the repos in Free/PRO to better server those with PRO.

We were doing a lot of changes from BS3 to BS4 in the structure of the product in order to comply with the latest Bootstrap rules. Sorry for the inconvenience, we will have a fix on this soon.

Best,
Alex

**Comment by bbuehrle** [comment]
I have the same issue using symfony 4 and webpack-encore.  I'm assuming that the `webpacker` gem is probably the same thing, but works with symfony.  I'm still new and I haven't fully tested, but the work-around that I came up with for now is to comment out `carousel.scss` from the main .scss file if you aren't using the carousel.

@alexandru-paduraru I have to disagree with your "better support" comment.  I hadn't seen this issue before I submitted mine in the PRO repo **16 DAYS** ago, but even with spending money on this kit I still haven't received a single comment.  I'm hoping that referencing it her on the free repo, it will draw more attention. creativetimofficial/material-kit-pro#63

**Comment by alexandru-paduraru** [comment]
@bbuehrle sorry to hear that :-( I've checked and I've seen that you don't have a response there either. We are looking into this and come back with a solution for you tomorrow.

**Comment by dragosct10** [comment]
Hi, @michelson! We are sorry for the late response. Now we tried to compile the scss with the rails app and yes there are errors. Did you fixed the errors, because I saw that you said that you fixed them? I've checked the errors and I fixed them so If you want I can send you the new `scss` folder to see if you still receive the errors. 

Regards,
Dragos

**Comment by michelson** [comment]
Hi Dragos , that would be great

thanks!

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by dragosct10** [comment]
Great! Please, give me your email to give you the dropbox link because here it's a public repo and I can't. Regards, Dragos

**Comment by michelson** [comment]
I've sen't you an email to dragos@creative-tim.com , thanks

**Comment by robertocarvajal** [comment]
I had the same problem with symfony and encore, I was able to find the missing arrow files browsing older versions of this repo, if everyone else needs them they can be downloaded from here

https://github.com/creativetimofficial/material-kit/tree/6d5e73894a6249e7081516def43e4d73cabcdb92/assets/img

once I put the files encore failed because it doesn't know how to handle .cur files but that's other issue, I just commented those out and it worked fine after that ;)

**Comment by mehdibaha** [comment]
Please fix this ASAP, as we can't have a working version-controlled package.json if the css contains bugs...

**Comment by dragosct10** [comment]
Hi, @mehdibaha! Thank you for using our product. We will release an update for the material kit in a few days. Regards, Dragos

**Comment by KgotsoK** [comment]
Has this been fixed?

Im using Angular 6, used npm to pull in the material-kit package, but `/node_modules/material-kit/assets/img` does not contain `arrow-right.cur` and `arrow-left.cur`. I mean this seems pretty straight-forward to fix doesn't it?
