### ISSUE TITLE
Using material kit along with Bootstrap

### ISSUE THREAD

**Issue by smohannagaraj** [creativetimofficial/material-kit#162]
I want to use Material kit only for the forms inside a bootstrap theme.  Is this is possible?
Please guide me.  If you want any other details, i will give you.
Thank you in advance

**Comment by groovemen** [comment]
Hello @smohannagaraj, 

Thank you for using our products, we are sorry for this late response! Hope that you found a solution to your question.  If not, we want to let you know that it will be hard work because this product is built over BootstrapMaterialDesign and if you want to use only a part of it, you have to integrate separately the Bootstrap files and in the **assets/scss/material-kit.scss** file you have to keep only the forms files.
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
