### ISSUE TITLE
How to use bootstrap loader?

### ISSUE THREAD

**Issue by shariful2011** [creativetimofficial/material-kit#170]
Thank you very much for this lovely framework. I am trying to implement bootstrap loader by the following code:

```
<div class="spinner-border" role="status">
  <span class="sr-only">Loading...</span>
</div>
```
nothing is happening, can you please guide or help?

**Comment by groovemen** [comment]
Hello @shariful2011,

Thank you for using our products, unfortunately this component isn't specific for Material Design. You can check the Bootstrap Material Design in order to check for it: https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/getting-started/introduction/

All the best, 
Stefan
