### ISSUE TITLE
rtl version

### ISSUE THREAD

**Issue by MetaiR** [creativetimofficial/material-kit#22]
do you have any plan for rtl version?

**Comment by alexandru-paduraru** [comment]
@MetaiR at this moment we don't have any plans for RTL because we didn't have requests for it yet. We have over 10k downloads on the free version and now is the first request. In order to keep the product simple and light we usually wait for 3-5 requests for a feature before we implement something. 

Hope you understand the situation and this makes sense for you.

Best,
Alex

**Comment by MetaiR** [comment]
I tortoly understand :)
I have started to make a RTL version and half of it is done until now
and i also include some extra and useful thing from other material kit or framework that i worked on them as extra-x.css and extra-x.js for example the colors for text and backgrounds
I hoped that you support me or at least confirm it if it's useful.

**Comment by MARGELANI** [comment]
Looking forward to have this with RTL support

**Comment by alexandru-paduraru** [comment]
@MARGELANI and @MetaiR there is one collaborator @shaheen who made the RTL version. We have to check it and then put it on this repo or link to his repo. We will talk with him to see exactly which is the best option to deliver the RTL to you. Tille then please get this archive made by him with the RTL version: https://www.dropbox.com/s/3xwqz7c4iyo7agy/material-kit-master-rtl.rar?dl=0

Best, 
Alex

**Comment by Bagmaz** [comment]
https://www.dropbox.com/s/3xwqz7c4iyo7agy/material-kit-master-rtl.rar?dl=0
this version has problem, please Fix RTL version
