### ISSUE TITLE
Menu mobile on all media screens

### ISSUE THREAD

**Issue by cegascam** [creativetimofficial/material-kit#78]
Hi to everyone, what do i have to change to make the mobile menu to be seen on all media sreens.
Thanks.

**Comment by groovemen** [comment]
Hello @cegascam, 

thank you for using our products, to use the mobile menu design of the navbar, you have to make the following changes:

- delete the class **navbar-expand-lg** from the `navbar`
- go to `responsive.scss` file and set all the media queries for the `navbar` to a bigger width (e.g. instead of **max-width: 991px** set to **max-width: 2880px**)

Hope this information helps you.
Best, 
Stefan

**Comment by groovemen** [comment]
Hello again, 

I reproduced again the steps from above and this is the result:
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/21063398/48844616-10140600-eda3-11e8-9ac6-f4f68899fdd0.gif)

All the best, 
Stefan
