### ISSUE TITLE
Adjust placement of toggle on mobile for navbar?

### ISSUE THREAD

**Issue by UnknownLuck** [creativetimofficial/material-kit#94]
I have been fiddling around for a while now, trying to figure out how to adjust the placement of the X for the navbar on mobile.  I adjusted the width of the menu to 70% so that it doesn't completely cover the screen, but it leaves the exit button almost entirely off the screen.  You can technically press the top left of the screen, but this is inconvenient and no one would know how to exit.

![site on mobile](https://user-images.githubusercontent.com/8964733/33530600-759ac558-d847-11e7-97c6-d4a455fe5dfa.png)

Any ideas that I can implement into my custom stylesheet to fix this? Thanks.

**Comment by dragosct10** [comment]
Hi, @UnknownLuck! Thank you for using our product. Please, can you give us the link to your project to see more exactly what happened there and we will try to help you?

Regards,
Dragos

**Comment by UnknownLuck** [comment]
My project can be found at unknownluck.github.io with all the code in the repo. This was happening on small mobile devices like the iPhone 4 and 5 for example. At bigger sizes, the exit button was close to the navigation menu as expected.

**Comment by dragosct10** [comment]
H, @UnknownLuck! The problem is that the navbar-collapse have a big width so automatically on the small screen size it will occupy much space from the screen. You have to do a small change to fix this problem and you have to reduce the translate on the Y side of the div with class `.navbar-translate` when the navbar-collapse is open. I will upload you a screenshot to see where you have to do this change. So like you see in the image now by default the div is translating on -300px. I changed to -250px and X toggle is appeared like it should be.

<img width="991" alt="screen shot 2017-12-05 at 12 39 35" src="https://user-images.githubusercontent.com/17456857/33603064-03578d54-d9ba-11e7-96de-dcc80a93fe7e.png">

**Comment by UnknownLuck** [comment]
This did work, thank you for that.  But now between these smaller devices and larger mobile devices, the exit button gets hidden by the navigation menu on the side. (Tested this by changing it to -250px and dragging the width of chrome around to see the exit button get hidden and then come back out at bigger widths.)

Would just adding a bunch of @media for different widths fix this? Or is there a more elegant solution?
